### ISSUE TITLE
Exodus 6.0.0 does not do anything when a movie is pressed

### ISSUE THREAD

**Issue by TheChosenEvilOne** [kodibae/repository.kodibae#8]

**Comment by eeden003** [comment]
One small issue however: when using MOVIES (cinema and/or new) the addon gives a nice list of movies. When selecting a movie the search starts searching but after a few moments the add-on freezes. Clicking on CANCEL has also no effect. When DE-Activating DIVXCRAWLER inside your add-on everything works perfectly again !.Keep on doing your good work !

**Comment by Andre19721972** [comment]
Same problem on 26 Aug. 2018 , see message frrom eeden003

**Comment by eeden003** [comment]
I've just looked at my version of Exodus 6.0.0.  At SETTINGS choose PROVIDERS and de-activate DIVXCRAWLER. Also check if DIVXCRAWLER is present in the URLresolver & ResolveUrl from TVAddonns are de-activarted íf present, I don't know if they are but do have a look at it.
If the problem is still present, please find someone with know-how, I am only a user and not an expert.
